import { instrumentSchema } from './instrument.js';

// Reviewed issuer share classes and exact Copenhagen/Xetra trading listings.
// Price availability is verified independently by the scheduled free-data job.
export const additionalFunds = [
  {
    id: 'sparindex-global',
    name: 'Sparindex INDEX Globale Aktier KL',
    shortName: 'Sparindex global equities',
    ticker: 'SPVIGAKL',
    exchange: 'Copenhagen',
    currency: 'DKK',
    kind: 'Fund',
    region: 'Global',
    isin: 'DK0060747822',
    mic: 'XCSE',
    yahooSymbol: 'SPVIGAKL.CO',
    yahooType: 'EQUITY',
    sourceKind: 'issuer',
    source: 'https://www.sparindex.dk/vores-fonde/index-globale-aktier-kl/',
    color: '#476d59',
    description:
      'A distributing Danish index fund covering global equities, including emerging markets and smaller companies. Currency exposure follows the underlying holdings.',
  },
  {
    id: 'sparindex-emerging',
    name: 'Sparindex INDEX Emerging Markets KL',
    shortName: 'Sparindex emerging markets',
    ticker: 'SPIEMIKL',
    exchange: 'Copenhagen',
    currency: 'DKK',
    kind: 'Fund',
    region: 'Emerging',
    isin: 'DK0060300762',
    mic: 'XCSE',
    yahooSymbol: 'SPIEMIKL.CO',
    yahooType: 'EQUITY',
    sourceKind: 'issuer',
    source: 'https://www.sparindex.dk/vores-fonde/index-emerging-markets-kl/',
    color: '#83612e',
    description:
      'A distributing Danish index fund tracking emerging-market equities. It provides a regional allocation rather than a complete global portfolio.',
  },
  {
    id: 'danske-global',
    name: 'Danske Invest Global Indeks, klasse DKK d',
    shortName: 'Danske Invest global index',
    ticker: 'DKIGI',
    exchange: 'Copenhagen',
    currency: 'DKK',
    kind: 'Fund',
    region: 'Developed',
    isin: 'DK0010263052',
    mic: 'XCSE',
    yahooSymbol: 'DKIGI.CO',
    yahooType: 'EQUITY',
    sourceKind: 'issuer',
    source:
      'https://www.danskeinvest.dk/w/show_funds.product?p_nFund=1873&p_nFundgroup=75&p_nId=75',
    color: '#506579',
    description:
      'A distributing Danish index fund following developed-market large and mid-sized equities. The DKK d share class has its own charges; institutional W classes are different investments.',
  },
  {
    id: 'nordea-global',
    name: 'Nordea Invest Globale Aktier Indeks KL 1',
    shortName: 'Nordea global equities index',
    ticker: 'NDIGAIKL1',
    exchange: 'Copenhagen',
    currency: 'DKK',
    kind: 'Fund',
    region: 'Developed',
    isin: 'DK0060451623',
    mic: 'XCSE',
    yahooSymbol: 'NDIGAIKL1.CO',
    yahooType: 'EQUITY',
    sourceKind: 'issuer',
    source: 'https://www.nordeafunds.com/da/fonde/globale-aktier-indeks-kl-1',
    color: '#396d6c',
    description:
      'A distributing Danish index fund tracking MSCI World developed-market equities. KL 1 and KL 2 are separate share classes.',
  },
  {
    id: 'spyi',
    name: 'State Street SPDR MSCI ACWI IMI UCITS ETF (Acc)',
    shortName: 'SPDR all-country all-cap',
    ticker: 'SPYI',
    exchange: 'XETR',
    currency: 'EUR',
    kind: 'ETF',
    region: 'Global',
    isin: 'IE00B3YLTY66',
    yahooSymbol: 'SPYI.DE',
    sourceKind: 'issuer',
    source:
      'https://www.ssga.com/ie/en_gb/intermediary/etfs/state-street-spdr-msci-all-country-world-investable-market-ucits-etf-acc-spyi-gy',
    color: '#476d59',
    description:
      'An accumulating UCITS ETF tracking developed and emerging-market equities, including small companies. This entry identifies the EUR Xetra listing.',
  },
  {
    id: 'sppw',
    name: 'State Street SPDR MSCI World UCITS ETF (Acc)',
    shortName: 'SPDR developed markets',
    ticker: 'SPPW',
    exchange: 'XETR',
    currency: 'EUR',
    kind: 'ETF',
    region: 'Developed',
    isin: 'IE00BFY0GT14',
    yahooSymbol: 'SPPW.DE',
    sourceKind: 'issuer',
    source:
      'https://www.ssga.com/ie/en_gb/intermediary/etfs/state-street-spdr-msci-world-ucits-etf-acc-sppw-gy',
    color: '#5f744f',
    description:
      'An accumulating UCITS ETF tracking developed-market large and mid-sized companies. Emerging markets are outside its benchmark.',
  },
  {
    id: 'eunk',
    name: 'iShares Core MSCI Europe UCITS ETF EUR (Acc)',
    shortName: 'European developed equities',
    ticker: 'EUNK',
    exchange: 'XETR',
    currency: 'EUR',
    kind: 'ETF',
    region: 'Europe',
    isin: 'IE00B4K48X80',
    yahooSymbol: 'EUNK.DE',
    sourceKind: 'issuer',
    source:
      'https://www.ishares.com/uk/individual/en/products/251861/ishares-msci-europe-ucits-etf-acc-fund',
    color: '#506579',
    description:
      'An accumulating UCITS ETF following developed European equities. It creates a regional allocation and overlaps with global equity funds.',
  },
  {
    id: 'iusn',
    name: 'iShares MSCI World Small Cap UCITS ETF USD (Acc)',
    shortName: 'Developed-market small companies',
    ticker: 'IUSN',
    exchange: 'XETR',
    currency: 'EUR',
    kind: 'ETF',
    region: 'Developed',
    isin: 'IE00BF4RFH31',
    yahooSymbol: 'IUSN.DE',
    sourceKind: 'issuer',
    source:
      'https://www.ishares.com/uk/individual/en/products/296576/ishares-msci-world-small-cap-ucits-etf-usd-acc-fund',
    color: '#83612e',
    description:
      'An accumulating UCITS ETF tracking smaller companies in developed markets. Share-class USD denomination is separate from this EUR trading listing.',
  },
].map((item) => instrumentSchema.parse(item));
